# docker logs -f jenkins
# 查看密码
version: '3'
services:
    jenkins:
        image: jenkins/jenkins:lts
        container_name: jenkins
        environment:
            - TZ=Asia/Shanghai
        volumes:
            - ./.docker/jenkins/jenkins_home:/var/jenkins_home
            # - /var/run/docker.sock:/var/run/docker.sock
            # - /usr/bin/docker:/usr/bin/docker
            # - /usr/lib/x86_64-linux-gnu/libltdl.so.7:/usr/lib/x86_64-linux-gnu/libltdl.so.7
        ports:
            - "8880:8080"
            - "50550:50000"
        privileged: true
        user: root
        restart: always
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - 4000:80
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./.docker/jenkins/jenkins_home/dist/build:/usr/share/nginx/html
networks:
  default:
    external:
    #   name: cra-test_default
       name: my-app_default