version: "3"
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile.static
    ports:
      - 3000:3000
  mongo:
    image: mongo
    restart: always
    container_name: 'mongo'
    ports:
      - 27017:27017 
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./.docker/mongo_data:/data/db
    networks:
      - default
    # docker exec -it mongo mongo
    # use demo db.auth('root', 'example')
    # db.createUser({ user: 'root', pwd: 'example', roles: [ { role: "dbOwner", db: "demo" } ] });

  mongo-express:
    image: mongo-express
    restart: always
    container_name: 'mongo-express'
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
networks:
  default:
    external:
      name: cra-test_default
      #  name: my-app_default