# 选择一个体积小的镜像 (~5MB)
FROM node:16-alpine

WORKDIR /code

# 单独分离 package.json，是为了安装依赖可最大限度利用缓存
ADD package.json yarn.lock /code/
# 此时，yarn 可以利用缓存，如果 yarn.lock 内容没有变化，则不会重新依赖安装
RUN yarn

ADD . /code

# 启动 Node Server
CMD npm build

EXPOSE 4004